language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make insitu.build ../insitu-duo.dk
  - cd ../insitu-duo.dk
  - sudo chmod -R 777 sites/all/modules
  - drush si insitu --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="insitu-duo.dk" --yes
  - drush cc all --yes

script: 
  - test -d profiles/insitu
  - test -d profiles/insitu/modules/contrib
  - test -d profiles/insitu/modules/in_situ_music
  - test -d profiles/insitu/themes
